FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY vite.config.js ./

RUN npm ci

COPY . .

RUN npm run build

RUN mkdir -p /app/backend_static && \
    cp -r dist/* /app/backend_static/
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]